/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as AmtAdminRouteImport } from './routes/amt-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as AmtAdminIndexRouteImport } from './routes/amt-admin.index'
import { Route as WidgetSuporteRouteImport } from './routes/widget.suporte'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as LpSlugRouteImport } from './routes/lp.$slug'
import { Route as CrmWorkflowsRouteImport } from './routes/crm.workflows'
import { Route as CrmWhatsappRouteImport } from './routes/crm.whatsapp'
import { Route as CrmTemplatesRouteImport } from './routes/crm.templates'
import { Route as CrmSequenciasRouteImport } from './routes/crm.sequencias'
import { Route as CrmRelatoriosRouteImport } from './routes/crm.relatorios'
import { Route as CrmPropostasRouteImport } from './routes/crm.propostas'
import { Route as CrmPosVendaRouteImport } from './routes/crm.pos-venda'
import { Route as CrmPortalRouteImport } from './routes/crm.portal'
import { Route as CrmPipelineRouteImport } from './routes/crm.pipeline'
import { Route as CrmOportunidadesRouteImport } from './routes/crm.oportunidades'
import { Route as CrmMensagensComerciaisRouteImport } from './routes/crm.mensagens-comerciais'
import { Route as CrmMensagensRouteImport } from './routes/crm.mensagens'
import { Route as CrmMarketingRouteImport } from './routes/crm.marketing'
import { Route as CrmLeadsRouteImport } from './routes/crm.leads'
import { Route as CrmLeadScraperRouteImport } from './routes/crm.lead-scraper'
import { Route as CrmLandingPagesRouteImport } from './routes/crm.landing-pages'
import { Route as CrmIntegracoesRouteImport } from './routes/crm.integracoes'
import { Route as CrmInstagramRouteImport } from './routes/crm.instagram'
import { Route as CrmIaImagensRouteImport } from './routes/crm.ia-imagens'
import { Route as CrmFinanceiroRouteImport } from './routes/crm.financeiro'
import { Route as CrmEmpresasRouteImport } from './routes/crm.empresas'
import { Route as CrmEmailRouteImport } from './routes/crm.email'
import { Route as CrmContratosRouteImport } from './routes/crm.contratos'
import { Route as CrmContasRouteImport } from './routes/crm.contas'
import { Route as CrmConfiguracoesRouteImport } from './routes/crm.configuracoes'
import { Route as CrmClientesRouteImport } from './routes/crm.clientes'
import { Route as CrmCanaisRouteImport } from './routes/crm.canais'
import { Route as CrmAutomacoesRouteImport } from './routes/crm.automacoes'
import { Route as CrmAssinaturasRouteImport } from './routes/crm.assinaturas'
import { Route as CrmAlertasRouteImport } from './routes/crm.alertas'
import { Route as CrmAgendaRouteImport } from './routes/crm.agenda'
import { Route as AmtAdminSistemasRouteImport } from './routes/amt-admin.sistemas'
import { Route as AmtAdminSegurancaRouteImport } from './routes/amt-admin.seguranca'
import { Route as AmtAdminPlanosRouteImport } from './routes/amt-admin.planos'
import { Route as AmtAdminModulosRouteImport } from './routes/amt-admin.modulos'
import { Route as AmtAdminComercialRouteImport } from './routes/amt-admin.comercial'
import { Route as AmtAdminClientesRouteImport } from './routes/amt-admin.clientes'
import { Route as AmtAdminAuditoriaRouteImport } from './routes/amt-admin.auditoria'
import { Route as AmtAdminAsaasRouteImport } from './routes/amt-admin.asaas'
import { Route as CrmLeadsIdRouteImport } from './routes/crm.leads.$id'
import { Route as ApiPublicPlanosSlugRouteImport } from './routes/api.public.planos.$slug'
import { Route as ApiPublicHooksScraperAutoRouteImport } from './routes/api.public.hooks.scraper-auto'
import { Route as ApiPublicHooksCrmWorkflowsTickRouteImport } from './routes/api.public.hooks.crm-workflows-tick'
import { Route as ApiPublicHooksCrmSequenciasTickRouteImport } from './routes/api.public.hooks.crm-sequencias-tick'
import { Route as ApiPublicHooksCrmScoringTickRouteImport } from './routes/api.public.hooks.crm-scoring-tick'
import { Route as ApiPublicHooksCrmMensagensTickRouteImport } from './routes/api.public.hooks.crm-mensagens-tick'
import { Route as ApiPublicHooksCrmLembretesTickRouteImport } from './routes/api.public.hooks.crm-lembretes-tick'
import { Route as ApiPublicHooksCrmInboxRouteImport } from './routes/api.public.hooks.crm-inbox'
import { Route as ApiPublicHooksCrmAlertasTickRouteImport } from './routes/api.public.hooks.crm-alertas-tick'
import { Route as ApiPublicHooksAsaasTickRouteImport } from './routes/api.public.hooks.asaas-tick'
import { Route as ApiPublicHooksAsaasRouteImport } from './routes/api.public.hooks.asaas'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AmtAdminRoute = AmtAdminRouteImport.update({
  id: '/amt-admin',
  path: '/amt-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const AmtAdminIndexRoute = AmtAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AmtAdminRoute,
} as any)
const WidgetSuporteRoute = WidgetSuporteRouteImport.update({
  id: '/widget/suporte',
  path: '/widget/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LpSlugRoute = LpSlugRouteImport.update({
  id: '/lp/$slug',
  path: '/lp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmWorkflowsRoute = CrmWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => CrmRoute,
} as any)
const CrmWhatsappRoute = CrmWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => CrmRoute,
} as any)
const CrmTemplatesRoute = CrmTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => CrmRoute,
} as any)
const CrmSequenciasRoute = CrmSequenciasRouteImport.update({
  id: '/sequencias',
  path: '/sequencias',
  getParentRoute: () => CrmRoute,
} as any)
const CrmRelatoriosRoute = CrmRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPropostasRoute = CrmPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPosVendaRoute = CrmPosVendaRouteImport.update({
  id: '/pos-venda',
  path: '/pos-venda',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPortalRoute = CrmPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPipelineRoute = CrmPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => CrmRoute,
} as any)
const CrmOportunidadesRoute = CrmOportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => CrmRoute,
} as any)
const CrmMensagensComerciaisRoute = CrmMensagensComerciaisRouteImport.update({
  id: '/mensagens-comerciais',
  path: '/mensagens-comerciais',
  getParentRoute: () => CrmRoute,
} as any)
const CrmMensagensRoute = CrmMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => CrmRoute,
} as any)
const CrmMarketingRoute = CrmMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadScraperRoute = CrmLeadScraperRouteImport.update({
  id: '/lead-scraper',
  path: '/lead-scraper',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLandingPagesRoute = CrmLandingPagesRouteImport.update({
  id: '/landing-pages',
  path: '/landing-pages',
  getParentRoute: () => CrmRoute,
} as any)
const CrmIntegracoesRoute = CrmIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => CrmRoute,
} as any)
const CrmInstagramRoute = CrmInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => CrmRoute,
} as any)
const CrmIaImagensRoute = CrmIaImagensRouteImport.update({
  id: '/ia-imagens',
  path: '/ia-imagens',
  getParentRoute: () => CrmRoute,
} as any)
const CrmFinanceiroRoute = CrmFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => CrmRoute,
} as any)
const CrmEmpresasRoute = CrmEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => CrmRoute,
} as any)
const CrmEmailRoute = CrmEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContratosRoute = CrmContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContasRoute = CrmContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => CrmRoute,
} as any)
const CrmConfiguracoesRoute = CrmConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => CrmRoute,
} as any)
const CrmClientesRoute = CrmClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCanaisRoute = CrmCanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAutomacoesRoute = CrmAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAssinaturasRoute = CrmAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAlertasRoute = CrmAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAgendaRoute = CrmAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => CrmRoute,
} as any)
const AmtAdminSistemasRoute = AmtAdminSistemasRouteImport.update({
  id: '/sistemas',
  path: '/sistemas',
  getParentRoute: () => AmtAdminRoute,
} as any)
const AmtAdminSegurancaRoute = AmtAdminSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AmtAdminRoute,
} as any)
const AmtAdminPlanosRoute = AmtAdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AmtAdminRoute,
} as any)
const AmtAdminModulosRoute = AmtAdminModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AmtAdminRoute,
} as any)
const AmtAdminComercialRoute = AmtAdminComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AmtAdminRoute,
} as any)
const AmtAdminClientesRoute = AmtAdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AmtAdminRoute,
} as any)
const AmtAdminAuditoriaRoute = AmtAdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AmtAdminRoute,
} as any)
const AmtAdminAsaasRoute = AmtAdminAsaasRouteImport.update({
  id: '/asaas',
  path: '/asaas',
  getParentRoute: () => AmtAdminRoute,
} as any)
const CrmLeadsIdRoute = CrmLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrmLeadsRoute,
} as any)
const ApiPublicPlanosSlugRoute = ApiPublicPlanosSlugRouteImport.update({
  id: '/api/public/planos/$slug',
  path: '/api/public/planos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScraperAutoRoute =
  ApiPublicHooksScraperAutoRouteImport.update({
    id: '/api/public/hooks/scraper-auto',
    path: '/api/public/hooks/scraper-auto',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCrmWorkflowsTickRoute =
  ApiPublicHooksCrmWorkflowsTickRouteImport.update({
    id: '/api/public/hooks/crm-workflows-tick',
    path: '/api/public/hooks/crm-workflows-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCrmSequenciasTickRoute =
  ApiPublicHooksCrmSequenciasTickRouteImport.update({
    id: '/api/public/hooks/crm-sequencias-tick',
    path: '/api/public/hooks/crm-sequencias-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCrmScoringTickRoute =
  ApiPublicHooksCrmScoringTickRouteImport.update({
    id: '/api/public/hooks/crm-scoring-tick',
    path: '/api/public/hooks/crm-scoring-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCrmMensagensTickRoute =
  ApiPublicHooksCrmMensagensTickRouteImport.update({
    id: '/api/public/hooks/crm-mensagens-tick',
    path: '/api/public/hooks/crm-mensagens-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCrmLembretesTickRoute =
  ApiPublicHooksCrmLembretesTickRouteImport.update({
    id: '/api/public/hooks/crm-lembretes-tick',
    path: '/api/public/hooks/crm-lembretes-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCrmInboxRoute = ApiPublicHooksCrmInboxRouteImport.update({
  id: '/api/public/hooks/crm-inbox',
  path: '/api/public/hooks/crm-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCrmAlertasTickRoute =
  ApiPublicHooksCrmAlertasTickRouteImport.update({
    id: '/api/public/hooks/crm-alertas-tick',
    path: '/api/public/hooks/crm-alertas-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAsaasTickRoute = ApiPublicHooksAsaasTickRouteImport.update({
  id: '/api/public/hooks/asaas-tick',
  path: '/api/public/hooks/asaas-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAsaasRoute = ApiPublicHooksAsaasRouteImport.update({
  id: '/api/public/hooks/asaas',
  path: '/api/public/hooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amt-admin': typeof AmtAdminRouteWithChildren
  '/crm': typeof CrmRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/amt-admin/asaas': typeof AmtAdminAsaasRoute
  '/amt-admin/auditoria': typeof AmtAdminAuditoriaRoute
  '/amt-admin/clientes': typeof AmtAdminClientesRoute
  '/amt-admin/comercial': typeof AmtAdminComercialRoute
  '/amt-admin/modulos': typeof AmtAdminModulosRoute
  '/amt-admin/planos': typeof AmtAdminPlanosRoute
  '/amt-admin/seguranca': typeof AmtAdminSegurancaRoute
  '/amt-admin/sistemas': typeof AmtAdminSistemasRoute
  '/crm/agenda': typeof CrmAgendaRoute
  '/crm/alertas': typeof CrmAlertasRoute
  '/crm/assinaturas': typeof CrmAssinaturasRoute
  '/crm/automacoes': typeof CrmAutomacoesRoute
  '/crm/canais': typeof CrmCanaisRoute
  '/crm/clientes': typeof CrmClientesRoute
  '/crm/configuracoes': typeof CrmConfiguracoesRoute
  '/crm/contas': typeof CrmContasRoute
  '/crm/contratos': typeof CrmContratosRoute
  '/crm/email': typeof CrmEmailRoute
  '/crm/empresas': typeof CrmEmpresasRoute
  '/crm/financeiro': typeof CrmFinanceiroRoute
  '/crm/ia-imagens': typeof CrmIaImagensRoute
  '/crm/instagram': typeof CrmInstagramRoute
  '/crm/integracoes': typeof CrmIntegracoesRoute
  '/crm/landing-pages': typeof CrmLandingPagesRoute
  '/crm/lead-scraper': typeof CrmLeadScraperRoute
  '/crm/leads': typeof CrmLeadsRouteWithChildren
  '/crm/marketing': typeof CrmMarketingRoute
  '/crm/mensagens': typeof CrmMensagensRoute
  '/crm/mensagens-comerciais': typeof CrmMensagensComerciaisRoute
  '/crm/oportunidades': typeof CrmOportunidadesRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/portal': typeof CrmPortalRoute
  '/crm/pos-venda': typeof CrmPosVendaRoute
  '/crm/propostas': typeof CrmPropostasRoute
  '/crm/relatorios': typeof CrmRelatoriosRoute
  '/crm/sequencias': typeof CrmSequenciasRoute
  '/crm/templates': typeof CrmTemplatesRoute
  '/crm/whatsapp': typeof CrmWhatsappRoute
  '/crm/workflows': typeof CrmWorkflowsRoute
  '/lp/$slug': typeof LpSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/widget/suporte': typeof WidgetSuporteRoute
  '/amt-admin/': typeof AmtAdminIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/crm/leads/$id': typeof CrmLeadsIdRoute
  '/api/public/hooks/asaas': typeof ApiPublicHooksAsaasRoute
  '/api/public/hooks/asaas-tick': typeof ApiPublicHooksAsaasTickRoute
  '/api/public/hooks/crm-alertas-tick': typeof ApiPublicHooksCrmAlertasTickRoute
  '/api/public/hooks/crm-inbox': typeof ApiPublicHooksCrmInboxRoute
  '/api/public/hooks/crm-lembretes-tick': typeof ApiPublicHooksCrmLembretesTickRoute
  '/api/public/hooks/crm-mensagens-tick': typeof ApiPublicHooksCrmMensagensTickRoute
  '/api/public/hooks/crm-scoring-tick': typeof ApiPublicHooksCrmScoringTickRoute
  '/api/public/hooks/crm-sequencias-tick': typeof ApiPublicHooksCrmSequenciasTickRoute
  '/api/public/hooks/crm-workflows-tick': typeof ApiPublicHooksCrmWorkflowsTickRoute
  '/api/public/hooks/scraper-auto': typeof ApiPublicHooksScraperAutoRoute
  '/api/public/planos/$slug': typeof ApiPublicPlanosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/amt-admin/asaas': typeof AmtAdminAsaasRoute
  '/amt-admin/auditoria': typeof AmtAdminAuditoriaRoute
  '/amt-admin/clientes': typeof AmtAdminClientesRoute
  '/amt-admin/comercial': typeof AmtAdminComercialRoute
  '/amt-admin/modulos': typeof AmtAdminModulosRoute
  '/amt-admin/planos': typeof AmtAdminPlanosRoute
  '/amt-admin/seguranca': typeof AmtAdminSegurancaRoute
  '/amt-admin/sistemas': typeof AmtAdminSistemasRoute
  '/crm/agenda': typeof CrmAgendaRoute
  '/crm/alertas': typeof CrmAlertasRoute
  '/crm/assinaturas': typeof CrmAssinaturasRoute
  '/crm/automacoes': typeof CrmAutomacoesRoute
  '/crm/canais': typeof CrmCanaisRoute
  '/crm/clientes': typeof CrmClientesRoute
  '/crm/configuracoes': typeof CrmConfiguracoesRoute
  '/crm/contas': typeof CrmContasRoute
  '/crm/contratos': typeof CrmContratosRoute
  '/crm/email': typeof CrmEmailRoute
  '/crm/empresas': typeof CrmEmpresasRoute
  '/crm/financeiro': typeof CrmFinanceiroRoute
  '/crm/ia-imagens': typeof CrmIaImagensRoute
  '/crm/instagram': typeof CrmInstagramRoute
  '/crm/integracoes': typeof CrmIntegracoesRoute
  '/crm/landing-pages': typeof CrmLandingPagesRoute
  '/crm/lead-scraper': typeof CrmLeadScraperRoute
  '/crm/leads': typeof CrmLeadsRouteWithChildren
  '/crm/marketing': typeof CrmMarketingRoute
  '/crm/mensagens': typeof CrmMensagensRoute
  '/crm/mensagens-comerciais': typeof CrmMensagensComerciaisRoute
  '/crm/oportunidades': typeof CrmOportunidadesRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/portal': typeof CrmPortalRoute
  '/crm/pos-venda': typeof CrmPosVendaRoute
  '/crm/propostas': typeof CrmPropostasRoute
  '/crm/relatorios': typeof CrmRelatoriosRoute
  '/crm/sequencias': typeof CrmSequenciasRoute
  '/crm/templates': typeof CrmTemplatesRoute
  '/crm/whatsapp': typeof CrmWhatsappRoute
  '/crm/workflows': typeof CrmWorkflowsRoute
  '/lp/$slug': typeof LpSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/widget/suporte': typeof WidgetSuporteRoute
  '/amt-admin': typeof AmtAdminIndexRoute
  '/crm': typeof CrmIndexRoute
  '/crm/leads/$id': typeof CrmLeadsIdRoute
  '/api/public/hooks/asaas': typeof ApiPublicHooksAsaasRoute
  '/api/public/hooks/asaas-tick': typeof ApiPublicHooksAsaasTickRoute
  '/api/public/hooks/crm-alertas-tick': typeof ApiPublicHooksCrmAlertasTickRoute
  '/api/public/hooks/crm-inbox': typeof ApiPublicHooksCrmInboxRoute
  '/api/public/hooks/crm-lembretes-tick': typeof ApiPublicHooksCrmLembretesTickRoute
  '/api/public/hooks/crm-mensagens-tick': typeof ApiPublicHooksCrmMensagensTickRoute
  '/api/public/hooks/crm-scoring-tick': typeof ApiPublicHooksCrmScoringTickRoute
  '/api/public/hooks/crm-sequencias-tick': typeof ApiPublicHooksCrmSequenciasTickRoute
  '/api/public/hooks/crm-workflows-tick': typeof ApiPublicHooksCrmWorkflowsTickRoute
  '/api/public/hooks/scraper-auto': typeof ApiPublicHooksScraperAutoRoute
  '/api/public/planos/$slug': typeof ApiPublicPlanosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amt-admin': typeof AmtAdminRouteWithChildren
  '/crm': typeof CrmRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/amt-admin/asaas': typeof AmtAdminAsaasRoute
  '/amt-admin/auditoria': typeof AmtAdminAuditoriaRoute
  '/amt-admin/clientes': typeof AmtAdminClientesRoute
  '/amt-admin/comercial': typeof AmtAdminComercialRoute
  '/amt-admin/modulos': typeof AmtAdminModulosRoute
  '/amt-admin/planos': typeof AmtAdminPlanosRoute
  '/amt-admin/seguranca': typeof AmtAdminSegurancaRoute
  '/amt-admin/sistemas': typeof AmtAdminSistemasRoute
  '/crm/agenda': typeof CrmAgendaRoute
  '/crm/alertas': typeof CrmAlertasRoute
  '/crm/assinaturas': typeof CrmAssinaturasRoute
  '/crm/automacoes': typeof CrmAutomacoesRoute
  '/crm/canais': typeof CrmCanaisRoute
  '/crm/clientes': typeof CrmClientesRoute
  '/crm/configuracoes': typeof CrmConfiguracoesRoute
  '/crm/contas': typeof CrmContasRoute
  '/crm/contratos': typeof CrmContratosRoute
  '/crm/email': typeof CrmEmailRoute
  '/crm/empresas': typeof CrmEmpresasRoute
  '/crm/financeiro': typeof CrmFinanceiroRoute
  '/crm/ia-imagens': typeof CrmIaImagensRoute
  '/crm/instagram': typeof CrmInstagramRoute
  '/crm/integracoes': typeof CrmIntegracoesRoute
  '/crm/landing-pages': typeof CrmLandingPagesRoute
  '/crm/lead-scraper': typeof CrmLeadScraperRoute
  '/crm/leads': typeof CrmLeadsRouteWithChildren
  '/crm/marketing': typeof CrmMarketingRoute
  '/crm/mensagens': typeof CrmMensagensRoute
  '/crm/mensagens-comerciais': typeof CrmMensagensComerciaisRoute
  '/crm/oportunidades': typeof CrmOportunidadesRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/portal': typeof CrmPortalRoute
  '/crm/pos-venda': typeof CrmPosVendaRoute
  '/crm/propostas': typeof CrmPropostasRoute
  '/crm/relatorios': typeof CrmRelatoriosRoute
  '/crm/sequencias': typeof CrmSequenciasRoute
  '/crm/templates': typeof CrmTemplatesRoute
  '/crm/whatsapp': typeof CrmWhatsappRoute
  '/crm/workflows': typeof CrmWorkflowsRoute
  '/lp/$slug': typeof LpSlugRoute
  '/portal/$token': typeof PortalTokenRoute
  '/widget/suporte': typeof WidgetSuporteRoute
  '/amt-admin/': typeof AmtAdminIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/crm/leads/$id': typeof CrmLeadsIdRoute
  '/api/public/hooks/asaas': typeof ApiPublicHooksAsaasRoute
  '/api/public/hooks/asaas-tick': typeof ApiPublicHooksAsaasTickRoute
  '/api/public/hooks/crm-alertas-tick': typeof ApiPublicHooksCrmAlertasTickRoute
  '/api/public/hooks/crm-inbox': typeof ApiPublicHooksCrmInboxRoute
  '/api/public/hooks/crm-lembretes-tick': typeof ApiPublicHooksCrmLembretesTickRoute
  '/api/public/hooks/crm-mensagens-tick': typeof ApiPublicHooksCrmMensagensTickRoute
  '/api/public/hooks/crm-scoring-tick': typeof ApiPublicHooksCrmScoringTickRoute
  '/api/public/hooks/crm-sequencias-tick': typeof ApiPublicHooksCrmSequenciasTickRoute
  '/api/public/hooks/crm-workflows-tick': typeof ApiPublicHooksCrmWorkflowsTickRoute
  '/api/public/hooks/scraper-auto': typeof ApiPublicHooksScraperAutoRoute
  '/api/public/planos/$slug': typeof ApiPublicPlanosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amt-admin'
    | '/crm'
    | '/privacidade'
    | '/suporte'
    | '/termos'
    | '/amt-admin/asaas'
    | '/amt-admin/auditoria'
    | '/amt-admin/clientes'
    | '/amt-admin/comercial'
    | '/amt-admin/modulos'
    | '/amt-admin/planos'
    | '/amt-admin/seguranca'
    | '/amt-admin/sistemas'
    | '/crm/agenda'
    | '/crm/alertas'
    | '/crm/assinaturas'
    | '/crm/automacoes'
    | '/crm/canais'
    | '/crm/clientes'
    | '/crm/configuracoes'
    | '/crm/contas'
    | '/crm/contratos'
    | '/crm/email'
    | '/crm/empresas'
    | '/crm/financeiro'
    | '/crm/ia-imagens'
    | '/crm/instagram'
    | '/crm/integracoes'
    | '/crm/landing-pages'
    | '/crm/lead-scraper'
    | '/crm/leads'
    | '/crm/marketing'
    | '/crm/mensagens'
    | '/crm/mensagens-comerciais'
    | '/crm/oportunidades'
    | '/crm/pipeline'
    | '/crm/portal'
    | '/crm/pos-venda'
    | '/crm/propostas'
    | '/crm/relatorios'
    | '/crm/sequencias'
    | '/crm/templates'
    | '/crm/whatsapp'
    | '/crm/workflows'
    | '/lp/$slug'
    | '/portal/$token'
    | '/widget/suporte'
    | '/amt-admin/'
    | '/crm/'
    | '/crm/leads/$id'
    | '/api/public/hooks/asaas'
    | '/api/public/hooks/asaas-tick'
    | '/api/public/hooks/crm-alertas-tick'
    | '/api/public/hooks/crm-inbox'
    | '/api/public/hooks/crm-lembretes-tick'
    | '/api/public/hooks/crm-mensagens-tick'
    | '/api/public/hooks/crm-scoring-tick'
    | '/api/public/hooks/crm-sequencias-tick'
    | '/api/public/hooks/crm-workflows-tick'
    | '/api/public/hooks/scraper-auto'
    | '/api/public/planos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacidade'
    | '/suporte'
    | '/termos'
    | '/amt-admin/asaas'
    | '/amt-admin/auditoria'
    | '/amt-admin/clientes'
    | '/amt-admin/comercial'
    | '/amt-admin/modulos'
    | '/amt-admin/planos'
    | '/amt-admin/seguranca'
    | '/amt-admin/sistemas'
    | '/crm/agenda'
    | '/crm/alertas'
    | '/crm/assinaturas'
    | '/crm/automacoes'
    | '/crm/canais'
    | '/crm/clientes'
    | '/crm/configuracoes'
    | '/crm/contas'
    | '/crm/contratos'
    | '/crm/email'
    | '/crm/empresas'
    | '/crm/financeiro'
    | '/crm/ia-imagens'
    | '/crm/instagram'
    | '/crm/integracoes'
    | '/crm/landing-pages'
    | '/crm/lead-scraper'
    | '/crm/leads'
    | '/crm/marketing'
    | '/crm/mensagens'
    | '/crm/mensagens-comerciais'
    | '/crm/oportunidades'
    | '/crm/pipeline'
    | '/crm/portal'
    | '/crm/pos-venda'
    | '/crm/propostas'
    | '/crm/relatorios'
    | '/crm/sequencias'
    | '/crm/templates'
    | '/crm/whatsapp'
    | '/crm/workflows'
    | '/lp/$slug'
    | '/portal/$token'
    | '/widget/suporte'
    | '/amt-admin'
    | '/crm'
    | '/crm/leads/$id'
    | '/api/public/hooks/asaas'
    | '/api/public/hooks/asaas-tick'
    | '/api/public/hooks/crm-alertas-tick'
    | '/api/public/hooks/crm-inbox'
    | '/api/public/hooks/crm-lembretes-tick'
    | '/api/public/hooks/crm-mensagens-tick'
    | '/api/public/hooks/crm-scoring-tick'
    | '/api/public/hooks/crm-sequencias-tick'
    | '/api/public/hooks/crm-workflows-tick'
    | '/api/public/hooks/scraper-auto'
    | '/api/public/planos/$slug'
  id:
    | '__root__'
    | '/'
    | '/amt-admin'
    | '/crm'
    | '/privacidade'
    | '/suporte'
    | '/termos'
    | '/amt-admin/asaas'
    | '/amt-admin/auditoria'
    | '/amt-admin/clientes'
    | '/amt-admin/comercial'
    | '/amt-admin/modulos'
    | '/amt-admin/planos'
    | '/amt-admin/seguranca'
    | '/amt-admin/sistemas'
    | '/crm/agenda'
    | '/crm/alertas'
    | '/crm/assinaturas'
    | '/crm/automacoes'
    | '/crm/canais'
    | '/crm/clientes'
    | '/crm/configuracoes'
    | '/crm/contas'
    | '/crm/contratos'
    | '/crm/email'
    | '/crm/empresas'
    | '/crm/financeiro'
    | '/crm/ia-imagens'
    | '/crm/instagram'
    | '/crm/integracoes'
    | '/crm/landing-pages'
    | '/crm/lead-scraper'
    | '/crm/leads'
    | '/crm/marketing'
    | '/crm/mensagens'
    | '/crm/mensagens-comerciais'
    | '/crm/oportunidades'
    | '/crm/pipeline'
    | '/crm/portal'
    | '/crm/pos-venda'
    | '/crm/propostas'
    | '/crm/relatorios'
    | '/crm/sequencias'
    | '/crm/templates'
    | '/crm/whatsapp'
    | '/crm/workflows'
    | '/lp/$slug'
    | '/portal/$token'
    | '/widget/suporte'
    | '/amt-admin/'
    | '/crm/'
    | '/crm/leads/$id'
    | '/api/public/hooks/asaas'
    | '/api/public/hooks/asaas-tick'
    | '/api/public/hooks/crm-alertas-tick'
    | '/api/public/hooks/crm-inbox'
    | '/api/public/hooks/crm-lembretes-tick'
    | '/api/public/hooks/crm-mensagens-tick'
    | '/api/public/hooks/crm-scoring-tick'
    | '/api/public/hooks/crm-sequencias-tick'
    | '/api/public/hooks/crm-workflows-tick'
    | '/api/public/hooks/scraper-auto'
    | '/api/public/planos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmtAdminRoute: typeof AmtAdminRouteWithChildren
  CrmRoute: typeof CrmRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  LpSlugRoute: typeof LpSlugRoute
  PortalTokenRoute: typeof PortalTokenRoute
  WidgetSuporteRoute: typeof WidgetSuporteRoute
  ApiPublicHooksAsaasRoute: typeof ApiPublicHooksAsaasRoute
  ApiPublicHooksAsaasTickRoute: typeof ApiPublicHooksAsaasTickRoute
  ApiPublicHooksCrmAlertasTickRoute: typeof ApiPublicHooksCrmAlertasTickRoute
  ApiPublicHooksCrmInboxRoute: typeof ApiPublicHooksCrmInboxRoute
  ApiPublicHooksCrmLembretesTickRoute: typeof ApiPublicHooksCrmLembretesTickRoute
  ApiPublicHooksCrmMensagensTickRoute: typeof ApiPublicHooksCrmMensagensTickRoute
  ApiPublicHooksCrmScoringTickRoute: typeof ApiPublicHooksCrmScoringTickRoute
  ApiPublicHooksCrmSequenciasTickRoute: typeof ApiPublicHooksCrmSequenciasTickRoute
  ApiPublicHooksCrmWorkflowsTickRoute: typeof ApiPublicHooksCrmWorkflowsTickRoute
  ApiPublicHooksScraperAutoRoute: typeof ApiPublicHooksScraperAutoRoute
  ApiPublicPlanosSlugRoute: typeof ApiPublicPlanosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amt-admin': {
      id: '/amt-admin'
      path: '/amt-admin'
      fullPath: '/amt-admin'
      preLoaderRoute: typeof AmtAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/amt-admin/': {
      id: '/amt-admin/'
      path: '/'
      fullPath: '/amt-admin/'
      preLoaderRoute: typeof AmtAdminIndexRouteImport
      parentRoute: typeof AmtAdminRoute
    }
    '/widget/suporte': {
      id: '/widget/suporte'
      path: '/widget/suporte'
      fullPath: '/widget/suporte'
      preLoaderRoute: typeof WidgetSuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/workflows': {
      id: '/crm/workflows'
      path: '/workflows'
      fullPath: '/crm/workflows'
      preLoaderRoute: typeof CrmWorkflowsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/whatsapp': {
      id: '/crm/whatsapp'
      path: '/whatsapp'
      fullPath: '/crm/whatsapp'
      preLoaderRoute: typeof CrmWhatsappRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/templates': {
      id: '/crm/templates'
      path: '/templates'
      fullPath: '/crm/templates'
      preLoaderRoute: typeof CrmTemplatesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/sequencias': {
      id: '/crm/sequencias'
      path: '/sequencias'
      fullPath: '/crm/sequencias'
      preLoaderRoute: typeof CrmSequenciasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/relatorios': {
      id: '/crm/relatorios'
      path: '/relatorios'
      fullPath: '/crm/relatorios'
      preLoaderRoute: typeof CrmRelatoriosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/propostas': {
      id: '/crm/propostas'
      path: '/propostas'
      fullPath: '/crm/propostas'
      preLoaderRoute: typeof CrmPropostasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/pos-venda': {
      id: '/crm/pos-venda'
      path: '/pos-venda'
      fullPath: '/crm/pos-venda'
      preLoaderRoute: typeof CrmPosVendaRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/portal': {
      id: '/crm/portal'
      path: '/portal'
      fullPath: '/crm/portal'
      preLoaderRoute: typeof CrmPortalRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/pipeline': {
      id: '/crm/pipeline'
      path: '/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof CrmPipelineRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/oportunidades': {
      id: '/crm/oportunidades'
      path: '/oportunidades'
      fullPath: '/crm/oportunidades'
      preLoaderRoute: typeof CrmOportunidadesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/mensagens-comerciais': {
      id: '/crm/mensagens-comerciais'
      path: '/mensagens-comerciais'
      fullPath: '/crm/mensagens-comerciais'
      preLoaderRoute: typeof CrmMensagensComerciaisRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/mensagens': {
      id: '/crm/mensagens'
      path: '/mensagens'
      fullPath: '/crm/mensagens'
      preLoaderRoute: typeof CrmMensagensRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/marketing': {
      id: '/crm/marketing'
      path: '/marketing'
      fullPath: '/crm/marketing'
      preLoaderRoute: typeof CrmMarketingRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/lead-scraper': {
      id: '/crm/lead-scraper'
      path: '/lead-scraper'
      fullPath: '/crm/lead-scraper'
      preLoaderRoute: typeof CrmLeadScraperRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/landing-pages': {
      id: '/crm/landing-pages'
      path: '/landing-pages'
      fullPath: '/crm/landing-pages'
      preLoaderRoute: typeof CrmLandingPagesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/integracoes': {
      id: '/crm/integracoes'
      path: '/integracoes'
      fullPath: '/crm/integracoes'
      preLoaderRoute: typeof CrmIntegracoesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/instagram': {
      id: '/crm/instagram'
      path: '/instagram'
      fullPath: '/crm/instagram'
      preLoaderRoute: typeof CrmInstagramRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/ia-imagens': {
      id: '/crm/ia-imagens'
      path: '/ia-imagens'
      fullPath: '/crm/ia-imagens'
      preLoaderRoute: typeof CrmIaImagensRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/financeiro': {
      id: '/crm/financeiro'
      path: '/financeiro'
      fullPath: '/crm/financeiro'
      preLoaderRoute: typeof CrmFinanceiroRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/empresas': {
      id: '/crm/empresas'
      path: '/empresas'
      fullPath: '/crm/empresas'
      preLoaderRoute: typeof CrmEmpresasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/email': {
      id: '/crm/email'
      path: '/email'
      fullPath: '/crm/email'
      preLoaderRoute: typeof CrmEmailRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contratos': {
      id: '/crm/contratos'
      path: '/contratos'
      fullPath: '/crm/contratos'
      preLoaderRoute: typeof CrmContratosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contas': {
      id: '/crm/contas'
      path: '/contas'
      fullPath: '/crm/contas'
      preLoaderRoute: typeof CrmContasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/configuracoes': {
      id: '/crm/configuracoes'
      path: '/configuracoes'
      fullPath: '/crm/configuracoes'
      preLoaderRoute: typeof CrmConfiguracoesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/clientes': {
      id: '/crm/clientes'
      path: '/clientes'
      fullPath: '/crm/clientes'
      preLoaderRoute: typeof CrmClientesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/canais': {
      id: '/crm/canais'
      path: '/canais'
      fullPath: '/crm/canais'
      preLoaderRoute: typeof CrmCanaisRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/automacoes': {
      id: '/crm/automacoes'
      path: '/automacoes'
      fullPath: '/crm/automacoes'
      preLoaderRoute: typeof CrmAutomacoesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/assinaturas': {
      id: '/crm/assinaturas'
      path: '/assinaturas'
      fullPath: '/crm/assinaturas'
      preLoaderRoute: typeof CrmAssinaturasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/alertas': {
      id: '/crm/alertas'
      path: '/alertas'
      fullPath: '/crm/alertas'
      preLoaderRoute: typeof CrmAlertasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/agenda': {
      id: '/crm/agenda'
      path: '/agenda'
      fullPath: '/crm/agenda'
      preLoaderRoute: typeof CrmAgendaRouteImport
      parentRoute: typeof CrmRoute
    }
    '/amt-admin/sistemas': {
      id: '/amt-admin/sistemas'
      path: '/sistemas'
      fullPath: '/amt-admin/sistemas'
      preLoaderRoute: typeof AmtAdminSistemasRouteImport
      parentRoute: typeof AmtAdminRoute
    }
    '/amt-admin/seguranca': {
      id: '/amt-admin/seguranca'
      path: '/seguranca'
      fullPath: '/amt-admin/seguranca'
      preLoaderRoute: typeof AmtAdminSegurancaRouteImport
      parentRoute: typeof AmtAdminRoute
    }
    '/amt-admin/planos': {
      id: '/amt-admin/planos'
      path: '/planos'
      fullPath: '/amt-admin/planos'
      preLoaderRoute: typeof AmtAdminPlanosRouteImport
      parentRoute: typeof AmtAdminRoute
    }
    '/amt-admin/modulos': {
      id: '/amt-admin/modulos'
      path: '/modulos'
      fullPath: '/amt-admin/modulos'
      preLoaderRoute: typeof AmtAdminModulosRouteImport
      parentRoute: typeof AmtAdminRoute
    }
    '/amt-admin/comercial': {
      id: '/amt-admin/comercial'
      path: '/comercial'
      fullPath: '/amt-admin/comercial'
      preLoaderRoute: typeof AmtAdminComercialRouteImport
      parentRoute: typeof AmtAdminRoute
    }
    '/amt-admin/clientes': {
      id: '/amt-admin/clientes'
      path: '/clientes'
      fullPath: '/amt-admin/clientes'
      preLoaderRoute: typeof AmtAdminClientesRouteImport
      parentRoute: typeof AmtAdminRoute
    }
    '/amt-admin/auditoria': {
      id: '/amt-admin/auditoria'
      path: '/auditoria'
      fullPath: '/amt-admin/auditoria'
      preLoaderRoute: typeof AmtAdminAuditoriaRouteImport
      parentRoute: typeof AmtAdminRoute
    }
    '/amt-admin/asaas': {
      id: '/amt-admin/asaas'
      path: '/asaas'
      fullPath: '/amt-admin/asaas'
      preLoaderRoute: typeof AmtAdminAsaasRouteImport
      parentRoute: typeof AmtAdminRoute
    }
    '/crm/leads/$id': {
      id: '/crm/leads/$id'
      path: '/$id'
      fullPath: '/crm/leads/$id'
      preLoaderRoute: typeof CrmLeadsIdRouteImport
      parentRoute: typeof CrmLeadsRoute
    }
    '/api/public/planos/$slug': {
      id: '/api/public/planos/$slug'
      path: '/api/public/planos/$slug'
      fullPath: '/api/public/planos/$slug'
      preLoaderRoute: typeof ApiPublicPlanosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scraper-auto': {
      id: '/api/public/hooks/scraper-auto'
      path: '/api/public/hooks/scraper-auto'
      fullPath: '/api/public/hooks/scraper-auto'
      preLoaderRoute: typeof ApiPublicHooksScraperAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-workflows-tick': {
      id: '/api/public/hooks/crm-workflows-tick'
      path: '/api/public/hooks/crm-workflows-tick'
      fullPath: '/api/public/hooks/crm-workflows-tick'
      preLoaderRoute: typeof ApiPublicHooksCrmWorkflowsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-sequencias-tick': {
      id: '/api/public/hooks/crm-sequencias-tick'
      path: '/api/public/hooks/crm-sequencias-tick'
      fullPath: '/api/public/hooks/crm-sequencias-tick'
      preLoaderRoute: typeof ApiPublicHooksCrmSequenciasTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-scoring-tick': {
      id: '/api/public/hooks/crm-scoring-tick'
      path: '/api/public/hooks/crm-scoring-tick'
      fullPath: '/api/public/hooks/crm-scoring-tick'
      preLoaderRoute: typeof ApiPublicHooksCrmScoringTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-mensagens-tick': {
      id: '/api/public/hooks/crm-mensagens-tick'
      path: '/api/public/hooks/crm-mensagens-tick'
      fullPath: '/api/public/hooks/crm-mensagens-tick'
      preLoaderRoute: typeof ApiPublicHooksCrmMensagensTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-lembretes-tick': {
      id: '/api/public/hooks/crm-lembretes-tick'
      path: '/api/public/hooks/crm-lembretes-tick'
      fullPath: '/api/public/hooks/crm-lembretes-tick'
      preLoaderRoute: typeof ApiPublicHooksCrmLembretesTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-inbox': {
      id: '/api/public/hooks/crm-inbox'
      path: '/api/public/hooks/crm-inbox'
      fullPath: '/api/public/hooks/crm-inbox'
      preLoaderRoute: typeof ApiPublicHooksCrmInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-alertas-tick': {
      id: '/api/public/hooks/crm-alertas-tick'
      path: '/api/public/hooks/crm-alertas-tick'
      fullPath: '/api/public/hooks/crm-alertas-tick'
      preLoaderRoute: typeof ApiPublicHooksCrmAlertasTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/asaas-tick': {
      id: '/api/public/hooks/asaas-tick'
      path: '/api/public/hooks/asaas-tick'
      fullPath: '/api/public/hooks/asaas-tick'
      preLoaderRoute: typeof ApiPublicHooksAsaasTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/asaas': {
      id: '/api/public/hooks/asaas'
      path: '/api/public/hooks/asaas'
      fullPath: '/api/public/hooks/asaas'
      preLoaderRoute: typeof ApiPublicHooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AmtAdminRouteChildren {
  AmtAdminAsaasRoute: typeof AmtAdminAsaasRoute
  AmtAdminAuditoriaRoute: typeof AmtAdminAuditoriaRoute
  AmtAdminClientesRoute: typeof AmtAdminClientesRoute
  AmtAdminComercialRoute: typeof AmtAdminComercialRoute
  AmtAdminModulosRoute: typeof AmtAdminModulosRoute
  AmtAdminPlanosRoute: typeof AmtAdminPlanosRoute
  AmtAdminSegurancaRoute: typeof AmtAdminSegurancaRoute
  AmtAdminSistemasRoute: typeof AmtAdminSistemasRoute
  AmtAdminIndexRoute: typeof AmtAdminIndexRoute
}

const AmtAdminRouteChildren: AmtAdminRouteChildren = {
  AmtAdminAsaasRoute: AmtAdminAsaasRoute,
  AmtAdminAuditoriaRoute: AmtAdminAuditoriaRoute,
  AmtAdminClientesRoute: AmtAdminClientesRoute,
  AmtAdminComercialRoute: AmtAdminComercialRoute,
  AmtAdminModulosRoute: AmtAdminModulosRoute,
  AmtAdminPlanosRoute: AmtAdminPlanosRoute,
  AmtAdminSegurancaRoute: AmtAdminSegurancaRoute,
  AmtAdminSistemasRoute: AmtAdminSistemasRoute,
  AmtAdminIndexRoute: AmtAdminIndexRoute,
}

const AmtAdminRouteWithChildren = AmtAdminRoute._addFileChildren(
  AmtAdminRouteChildren,
)

interface CrmLeadsRouteChildren {
  CrmLeadsIdRoute: typeof CrmLeadsIdRoute
}

const CrmLeadsRouteChildren: CrmLeadsRouteChildren = {
  CrmLeadsIdRoute: CrmLeadsIdRoute,
}

const CrmLeadsRouteWithChildren = CrmLeadsRoute._addFileChildren(
  CrmLeadsRouteChildren,
)

interface CrmRouteChildren {
  CrmAgendaRoute: typeof CrmAgendaRoute
  CrmAlertasRoute: typeof CrmAlertasRoute
  CrmAssinaturasRoute: typeof CrmAssinaturasRoute
  CrmAutomacoesRoute: typeof CrmAutomacoesRoute
  CrmCanaisRoute: typeof CrmCanaisRoute
  CrmClientesRoute: typeof CrmClientesRoute
  CrmConfiguracoesRoute: typeof CrmConfiguracoesRoute
  CrmContasRoute: typeof CrmContasRoute
  CrmContratosRoute: typeof CrmContratosRoute
  CrmEmailRoute: typeof CrmEmailRoute
  CrmEmpresasRoute: typeof CrmEmpresasRoute
  CrmFinanceiroRoute: typeof CrmFinanceiroRoute
  CrmIaImagensRoute: typeof CrmIaImagensRoute
  CrmInstagramRoute: typeof CrmInstagramRoute
  CrmIntegracoesRoute: typeof CrmIntegracoesRoute
  CrmLandingPagesRoute: typeof CrmLandingPagesRoute
  CrmLeadScraperRoute: typeof CrmLeadScraperRoute
  CrmLeadsRoute: typeof CrmLeadsRouteWithChildren
  CrmMarketingRoute: typeof CrmMarketingRoute
  CrmMensagensRoute: typeof CrmMensagensRoute
  CrmMensagensComerciaisRoute: typeof CrmMensagensComerciaisRoute
  CrmOportunidadesRoute: typeof CrmOportunidadesRoute
  CrmPipelineRoute: typeof CrmPipelineRoute
  CrmPortalRoute: typeof CrmPortalRoute
  CrmPosVendaRoute: typeof CrmPosVendaRoute
  CrmPropostasRoute: typeof CrmPropostasRoute
  CrmRelatoriosRoute: typeof CrmRelatoriosRoute
  CrmSequenciasRoute: typeof CrmSequenciasRoute
  CrmTemplatesRoute: typeof CrmTemplatesRoute
  CrmWhatsappRoute: typeof CrmWhatsappRoute
  CrmWorkflowsRoute: typeof CrmWorkflowsRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmAgendaRoute: CrmAgendaRoute,
  CrmAlertasRoute: CrmAlertasRoute,
  CrmAssinaturasRoute: CrmAssinaturasRoute,
  CrmAutomacoesRoute: CrmAutomacoesRoute,
  CrmCanaisRoute: CrmCanaisRoute,
  CrmClientesRoute: CrmClientesRoute,
  CrmConfiguracoesRoute: CrmConfiguracoesRoute,
  CrmContasRoute: CrmContasRoute,
  CrmContratosRoute: CrmContratosRoute,
  CrmEmailRoute: CrmEmailRoute,
  CrmEmpresasRoute: CrmEmpresasRoute,
  CrmFinanceiroRoute: CrmFinanceiroRoute,
  CrmIaImagensRoute: CrmIaImagensRoute,
  CrmInstagramRoute: CrmInstagramRoute,
  CrmIntegracoesRoute: CrmIntegracoesRoute,
  CrmLandingPagesRoute: CrmLandingPagesRoute,
  CrmLeadScraperRoute: CrmLeadScraperRoute,
  CrmLeadsRoute: CrmLeadsRouteWithChildren,
  CrmMarketingRoute: CrmMarketingRoute,
  CrmMensagensRoute: CrmMensagensRoute,
  CrmMensagensComerciaisRoute: CrmMensagensComerciaisRoute,
  CrmOportunidadesRoute: CrmOportunidadesRoute,
  CrmPipelineRoute: CrmPipelineRoute,
  CrmPortalRoute: CrmPortalRoute,
  CrmPosVendaRoute: CrmPosVendaRoute,
  CrmPropostasRoute: CrmPropostasRoute,
  CrmRelatoriosRoute: CrmRelatoriosRoute,
  CrmSequenciasRoute: CrmSequenciasRoute,
  CrmTemplatesRoute: CrmTemplatesRoute,
  CrmWhatsappRoute: CrmWhatsappRoute,
  CrmWorkflowsRoute: CrmWorkflowsRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmtAdminRoute: AmtAdminRouteWithChildren,
  CrmRoute: CrmRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  LpSlugRoute: LpSlugRoute,
  PortalTokenRoute: PortalTokenRoute,
  WidgetSuporteRoute: WidgetSuporteRoute,
  ApiPublicHooksAsaasRoute: ApiPublicHooksAsaasRoute,
  ApiPublicHooksAsaasTickRoute: ApiPublicHooksAsaasTickRoute,
  ApiPublicHooksCrmAlertasTickRoute: ApiPublicHooksCrmAlertasTickRoute,
  ApiPublicHooksCrmInboxRoute: ApiPublicHooksCrmInboxRoute,
  ApiPublicHooksCrmLembretesTickRoute: ApiPublicHooksCrmLembretesTickRoute,
  ApiPublicHooksCrmMensagensTickRoute: ApiPublicHooksCrmMensagensTickRoute,
  ApiPublicHooksCrmScoringTickRoute: ApiPublicHooksCrmScoringTickRoute,
  ApiPublicHooksCrmSequenciasTickRoute: ApiPublicHooksCrmSequenciasTickRoute,
  ApiPublicHooksCrmWorkflowsTickRoute: ApiPublicHooksCrmWorkflowsTickRoute,
  ApiPublicHooksScraperAutoRoute: ApiPublicHooksScraperAutoRoute,
  ApiPublicPlanosSlugRoute: ApiPublicPlanosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
